import { Budget, Client, CatalogItem, Receivable, FinancialTransaction, Appointment, AppNotification, UserProfile, Equipment, PmocReport } from '../types';

export const INITIAL_PROFILE: UserProfile = {
  businessName: 'Aferix Soluções Elétricas & Manutenção',
  ownerName: 'Mateus Rossi',
  pixKey: 'mateus.eletrica@aferix.com.br',
  phone: '(11) 98765-4321',
  email: 'contato@aferix.com.br',
  city: 'São Paulo - SP',
  cnpj: '48.192.834/0001-90',
  technicalRegistry: 'CFT-SP 189420 / CREA 507029',
};

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'João Silva',
    phone: '(11) 99850-9999',
    email: 'joao.silva@email.com',
    city: 'São Paulo, SP',
    address: 'Rua das Acácias, 120 - Moema',
    notes: 'Cliente residencial, prefere atendimento pela manhã.',
    totalJobs: 4,
    totalRevenue: 6850,
  },
  {
    id: 'c2',
    name: 'Maria Oliveira',
    phone: '(11) 98896-8888',
    email: 'maria.adm@predial.com',
    city: 'São Paulo, SP',
    address: 'Av. Paulista, 1400 - Bela Vista',
    notes: 'Síndica do Edifício Solar das Flores.',
    totalJobs: 3,
    totalRevenue: 8400,
  },
  {
    id: 'c3',
    name: 'Carlos Pereira',
    phone: '(11) 97777-7777',
    email: 'carlos.comercio@gmail.com',
    city: 'Santo André, SP',
    address: 'Rua Coronel Oliveira, 305 - Centro',
    notes: 'Restaurante comercial. Manutenção de quadros elétricos.',
    totalJobs: 2,
    totalRevenue: 5600,
  },
  {
    id: 'c4',
    name: 'Ana Costa',
    phone: '(11) 96666-6666',
    email: 'ana.costa@tech.io',
    city: 'São Paulo, SP',
    address: 'Rua Funchal, 418 - Vila Olímpia',
    notes: 'Escritório de tecnologia.',
    totalJobs: 1,
    totalRevenue: 1250,
  },
  {
    id: 'c5',
    name: 'Fernanda Lima',
    phone: '(11) 95555-5555',
    city: 'Guarulhos, SP',
    address: 'Av. Tiradentes, 890 - Centro',
    notes: 'Galpão de distribuição.',
    totalJobs: 2,
    totalRevenue: 4880,
  },
  {
    id: 'c6',
    name: 'Roberto Santos',
    phone: '(11) 94444-4444',
    city: 'São Caetano do Sul, SP',
    address: 'Rua Goitacazes, 520 - Santa Paula',
    notes: 'Condomínio Residencial.',
    totalJobs: 5,
    totalRevenue: 9300,
  },
];

export const INITIAL_CATALOG: CatalogItem[] = [
  { id: 'k1', name: 'Instalação elétrica residencial (ponto padrão)', category: 'Serviço', unit: 'un', price: 180, cost: 45 },
  { id: 'k2', name: 'Manutenção preventiva quadro elétrico', category: 'Serviço', unit: 'un', price: 460, cost: 90 },
  { id: 'k3', name: 'Troca de fiação e reforma completa (por cômodo)', category: 'Serviço', unit: 'cômodo', price: 950, cost: 280 },
  { id: 'k4', name: 'Quadro de distribuição 12 disjuntores DIN', category: 'Material', unit: 'un', price: 650, cost: 420 },
  { id: 'k5', name: 'Disjuntor bipolar 40A curva C', category: 'Material', unit: 'un', price: 120, cost: 65 },
  { id: 'k6', name: 'Fio 6mm² flexível antichama (rolo 100m)', category: 'Material', unit: 'rolo', price: 850, cost: 610 },
  { id: 'k7', name: 'Tomada 20A com módulo e espelho', category: 'Material', unit: 'un', price: 35, cost: 16 },
  { id: 'k8', name: 'Mão de obra técnica especializada', category: 'Mão de obra', unit: 'hora', price: 110, cost: 35 },
  { id: 'k9', name: 'Instalação de sensor de presença & LED', category: 'Serviço', unit: 'un', price: 140, cost: 40 },
  { id: 'k10', name: 'Dispositivo DPS Clamper tetrapolar', category: 'Material', unit: 'un', price: 290, cost: 185 },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'b1025',
    code: '#1025',
    title: 'Instalação elétrica residencial e novo quadro',
    clientId: 'c1',
    clientName: 'João Silva',
    clientPhone: '(11) 99850-9999',
    clientAddress: 'Rua das Acácias, 120 - Moema, São Paulo - SP',
    status: 'aprovado',
    date: '2026-09-14',
    scheduledTime: '08:30',
    items: [
      { id: 'i1', name: 'Instalação elétrica residencial (ponto padrão)', type: 'servico', qty: 3, unit: 'un', unitPrice: 180, unitCost: 45, total: 540 },
      { id: 'i2', name: 'Quadro de distribuição 12 disjuntores DIN', type: 'material', qty: 1, unit: 'un', unitPrice: 650, unitCost: 420, total: 650 },
      { id: 'i3', name: 'Disjuntor bipolar 40A curva C', type: 'material', qty: 2, unit: 'un', unitPrice: 120, unitCost: 65, total: 240 },
      { id: 'i4', name: 'Fio 6mm² flexível antichama', type: 'material', qty: 1, unit: 'rolo', unitPrice: 850, unitCost: 610, total: 850 },
      { id: 'i5', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 4, unit: 'hora', unitPrice: 110, unitCost: 35, total: 440 },
      { id: 'i6', name: 'Tomada 20A com módulo e espelho', type: 'material', qty: 1, unit: 'un', unitPrice: 30, unitCost: 10, total: 30 },
    ],
    totalValue: 2750,
    totalCost: 1580,
    netProfit: 1170,
    marginPercent: 42.5,
    notes: 'Instalação agendada com aprovação prévia. Chave PIX cadastrada.',
    createdAt: '2026-09-12T10:00:00Z',
  },
  {
    id: 'b1024',
    code: '#1024',
    title: 'Manutenção predial preventiva e quadros gerais',
    clientId: 'c2',
    clientName: 'Maria Oliveira',
    clientPhone: '(11) 98896-8888',
    clientAddress: 'Av. Paulista, 1400 - Bela Vista, São Paulo - SP',
    status: 'execucao',
    date: '2026-09-14',
    scheduledTime: '14:00',
    items: [
      { id: 'i1', name: 'Manutenção preventiva quadro elétrico', type: 'servico', qty: 4, unit: 'un', unitPrice: 460, unitCost: 90, total: 1840 },
      { id: 'i2', name: 'Dispositivo DPS Clamper tetrapolar', type: 'material', qty: 2, unit: 'un', unitPrice: 290, unitCost: 185, total: 580 },
      { id: 'i3', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 13, unit: 'hora', unitPrice: 110, unitCost: 35, total: 1430 },
    ],
    totalValue: 3850,
    totalCost: 2387,
    netProfit: 1463,
    marginPercent: 38.0,
    notes: 'Serviço em execução no 4º andar.',
    createdAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'b1023',
    code: '#1023',
    title: 'Reforma elétrica geral do restaurante',
    clientId: 'c3',
    clientName: 'Carlos Pereira',
    clientPhone: '(11) 97777-7777',
    clientAddress: 'Rua Coronel Oliveira, 305 - Santo André - SP',
    status: 'aprovado',
    date: '2026-09-16',
    scheduledTime: '09:30',
    items: [
      { id: 'i1', name: 'Troca de fiação e reforma completa', type: 'servico', qty: 3, unit: 'cômodo', unitPrice: 950, unitCost: 280, total: 2850 },
      { id: 'i2', name: 'Fio 6mm² flexível antichama', type: 'material', qty: 2, unit: 'rolo', unitPrice: 850, unitCost: 610, total: 1700 },
      { id: 'i3', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 9.5, unit: 'hora', unitPrice: 110, unitCost: 35, total: 1050 },
    ],
    totalValue: 5600,
    totalCost: 3617,
    netProfit: 1983,
    marginPercent: 35.4,
    notes: 'Execução programada para o fechamento de segunda-feira.',
    createdAt: '2026-09-08T11:00:00Z',
  },
  {
    id: 'b1022',
    code: '#1022',
    title: 'Visita técnica diagnóstico e laudo de carga',
    clientId: 'c4',
    clientName: 'Ana Costa',
    clientPhone: '(11) 96666-6666',
    clientAddress: 'Rua Funchal, 418 - Vila Olímpia, São Paulo - SP',
    status: 'enviado',
    date: '2026-09-15',
    scheduledTime: '16:30',
    items: [
      { id: 'i1', name: 'Visita técnica especializada e diagnóstico', type: 'servico', qty: 1, unit: 'un', unitPrice: 650, unitCost: 150, total: 650 },
      { id: 'i2', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 5.45, unit: 'hora', unitPrice: 110, unitCost: 35, total: 600 },
    ],
    totalValue: 1250,
    totalCost: 610,
    netProfit: 640,
    marginPercent: 51.2,
    notes: 'Orçamento enviado por PDF via WhatsApp. Aguardando aprovação da diretoria.',
    createdAt: '2026-09-13T09:00:00Z',
  },
  {
    id: 'b1021',
    code: '#1021',
    title: 'Novo quadro de distribuição trifásico e barramentos',
    clientId: 'c5',
    clientName: 'Fernanda Lima',
    clientPhone: '(11) 95555-5555',
    clientAddress: 'Av. Tiradentes, 890 - Centro, Guarulhos - SP',
    status: 'iniciado',
    date: '2026-09-17',
    items: [
      { id: 'i1', name: 'Quadro de distribuição 12 disjuntores DIN', type: 'material', qty: 2, unit: 'un', unitPrice: 650, unitCost: 420, total: 1300 },
      { id: 'i2', name: 'Dispositivo DPS Clamper tetrapolar', type: 'material', qty: 2, unit: 'un', unitPrice: 290, unitCost: 185, total: 580 },
      { id: 'i3', name: 'Troca de fiação e reforma completa', type: 'servico', qty: 2, unit: 'cômodo', unitPrice: 950, unitCost: 280, total: 1900 },
      { id: 'i4', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 10, unit: 'hora', unitPrice: 110, unitCost: 35, total: 1100 },
    ],
    totalValue: 4880,
    totalCost: 2728,
    netProfit: 2152,
    marginPercent: 44.1,
    notes: 'Rascunho de levantamento em campo.',
    createdAt: '2026-09-14T08:00:00Z',
  },
  {
    id: 'b1020',
    code: '#1020',
    title: 'Padrão de entrada bifásico e homologação',
    clientId: 'c6',
    clientName: 'Roberto Santos',
    clientPhone: '(11) 94444-4444',
    clientAddress: 'Rua Goitacazes, 520 - São Caetano do Sul - SP',
    status: 'finalizado',
    date: '2026-09-10',
    items: [
      { id: 'i1', name: 'Instalação de padrão de entrada bifásico', type: 'servico', qty: 1, unit: 'un', unitPrice: 3800, unitCost: 2100, total: 3800 },
      { id: 'i2', name: 'Mão de obra técnica especializada', type: 'mao_de_obra', qty: 22.7, unit: 'hora', unitPrice: 110, unitCost: 35, total: 2500 },
    ],
    totalValue: 6300,
    totalCost: 3780,
    netProfit: 2520,
    marginPercent: 40.0,
    notes: 'Serviço finalizado com sucesso. Pagamento recebido via PIX.',
    createdAt: '2026-09-02T10:00:00Z',
    completedAt: '2026-09-10T17:00:00Z',
  },
];

export const INITIAL_RECEIVABLES: Receivable[] = [
  {
    id: 'r1',
    budgetId: 'b1025',
    clientName: 'João Silva',
    description: 'Orçamento #1025 - Parcela 1/2',
    value: 1375,
    dueDate: '2026-09-20',
    status: 'pendente',
  },
  {
    id: 'r2',
    budgetId: 'b1025',
    clientName: 'João Silva',
    description: 'Orçamento #1025 - Parcela 2/2',
    value: 1375,
    dueDate: '2026-10-05',
    status: 'pendente',
  },
  {
    id: 'r3',
    budgetId: 'b1024',
    clientName: 'Maria Oliveira',
    description: 'Orçamento #1024 - Manutenção predial',
    value: 3850,
    dueDate: '2026-09-25',
    status: 'pendente',
  },
  {
    id: 'r4',
    budgetId: 'b1023',
    clientName: 'Carlos Pereira',
    description: 'Orçamento #1023 - Entrada sinal 50%',
    value: 2800,
    dueDate: '2026-09-18',
    status: 'pendente',
  },
  {
    id: 'r5',
    budgetId: 'b1020',
    clientName: 'Roberto Santos',
    description: 'Orçamento #1020 - Conclusão Padrão',
    value: 6300,
    dueDate: '2026-09-10',
    status: 'recebido',
    receivedAt: '2026-09-10',
  },
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 't1',
    type: 'entrada',
    category: 'Serviço Finalizado',
    description: 'Recebimento Orçamento #1020 (Roberto Santos)',
    value: 6300,
    date: '2026-09-10',
    budgetId: 'b1020',
  },
  {
    id: 't2',
    type: 'saida',
    category: 'Materiais & Componentes',
    description: 'Compra de cabos 6mm² e disjuntores DIN (Distribuidora Elétrica)',
    value: 2450,
    date: '2026-09-11',
  },
  {
    id: 't3',
    type: 'saida',
    category: 'Combustível & Transporte',
    description: 'Abastecimento veículo de serviço - Visitas SP/ABC',
    value: 280,
    date: '2026-09-12',
  },
  {
    id: 't4',
    type: 'entrada',
    category: 'Sinal de Serviço',
    description: 'Sinal 50% reforma elétrica comercial (Carlos Pereira)',
    value: 2800,
    date: '2026-09-13',
    budgetId: 'b1023',
  },
  {
    id: 't5',
    type: 'saida',
    category: 'Ferramentas',
    description: 'Alicate decapador automático e multímetro digital True RMS',
    value: 390,
    date: '2026-09-13',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'a1',
    budgetId: 'b1025',
    clientId: 'c1',
    clientName: 'João Silva',
    title: 'Instalação Elétrica & Novo Quadro (#1025)',
    date: '2026-09-14',
    time: '08:30',
    address: 'Rua das Acácias, 120 - Moema, SP',
    status: 'agendado',
    type: 'execucao',
  },
  {
    id: 'a2',
    budgetId: 'b1024',
    clientId: 'c2',
    clientName: 'Maria Oliveira',
    title: 'Inspeção PMOC e Quadros Gerais (#1024)',
    date: '2026-09-14',
    time: '14:00',
    address: 'Av. Paulista, 1400 - Bela Vista, SP',
    status: 'em_andamento',
    type: 'execucao',
  },
  {
    id: 'a3',
    budgetId: 'b1022',
    clientId: 'c4',
    clientName: 'Ana Costa',
    title: 'Visita Técnica e Diagnóstico de Carga (#1022)',
    date: '2026-09-15',
    time: '16:30',
    address: 'Rua Funchal, 418 - Vila Olímpia, SP',
    status: 'agendado',
    type: 'visita_tecnica',
  },
  {
    id: 'a4',
    budgetId: 'b1023',
    clientId: 'c3',
    clientName: 'Carlos Pereira',
    title: 'Início da Reforma Elétrica do Restaurante (#1023)',
    date: '2026-09-16',
    time: '09:30',
    address: 'Rua Coronel Oliveira, 305 - Santo André, SP',
    status: 'agendado',
    type: 'execucao',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Sincronização Concluída',
    message: 'Banco local de dados Aferix sincronizado com segurança.',
    time: 'Agora mesmo',
    type: 'success',
    read: false,
  },
  {
    id: 'n2',
    title: 'Atendimento Agendado',
    message: 'Execução de OS #1025 agendada com João Silva hoje às 08:30.',
    time: 'Hoje, 07:00',
    type: 'info',
    read: false,
  },
  {
    id: 'n3',
    title: 'Orçamento Aprovado',
    message: 'Carlos Pereira aprovou a proposta #1023 (R$ 5.600,00).',
    time: 'Ontem',
    type: 'success',
    read: true,
  },
  {
    id: 'n4',
    title: 'Atenção a Recebíveis',
    message: 'Parcela de R$ 2.800,00 tem vencimento previsto para 18/09.',
    time: 'Ontem',
    type: 'warning',
    read: true,
  },
];

export const INITIAL_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq1',
    clientId: 'c3',
    clientName: 'Carlos Pereira',
    name: 'Quadro Geral de Baixa Tensão (QGBT)',
    brand: 'Schneider Electric',
    model: 'Prisma Plus P 630A',
    serialNumber: 'SCH-2024-8891',
    installDate: '2024-03-10',
    warrantyUntil: '2027-03-10',
    location: 'Subsolo 1 - Sala Técnica de Energia',
    status: 'operacional',
    lastMaintenance: '2026-06-15',
    notes: 'Revisão periódica de torque e termografia preventiva.',
  },
  {
    id: 'eq2',
    clientId: 'c1',
    clientName: 'João Silva',
    name: 'Quadro Distribuição Bifásico 80A',
    brand: 'Siemens',
    model: 'Simbox 24 DIN',
    serialNumber: 'SIE-99214-SP',
    installDate: '2025-01-15',
    warrantyUntil: '2026-01-15',
    location: 'Garagem Principal',
    status: 'operacional',
    lastMaintenance: '2026-09-14',
    notes: 'Novo barramento e DPS instalados.',
  },
  {
    id: 'eq3',
    clientId: 'c2',
    clientName: 'Maria Oliveira',
    name: 'Banco de Capacitores Automático',
    brand: 'WEG',
    model: 'UCW-T 25kvar',
    serialNumber: 'WEG-CAP-3310',
    installDate: '2023-11-20',
    warrantyUntil: '2025-11-20',
    location: 'Casa de Máquinas - Edifício Solar',
    status: 'manutencao_necessaria',
    lastMaintenance: '2025-12-05',
    notes: 'Necessário troca de contatoras de manobra capacitiva.',
  },
];

export const INITIAL_PMOC_REPORTS: PmocReport[] = [
  {
    id: 'pm1',
    code: 'PMP-2026-001',
    planType: 'pmp',
    discipline: 'eletrica',
    periodicity: 'trimestral',
    clientId: 'c3',
    clientName: 'Carlos Pereira',
    equipmentName: 'QGBT Schneider 630A & Subestação',
    technicianName: 'Mateus Rossi',
    date: '2026-09-10',
    generalStatus: 'aprovado',
    technicianNotes: 'Termografia realizada em plena carga operacional. Sem anomalias térmicas ou sobreaquecimento em barramentos.',
    clientSignatureName: 'Carlos Pereira (Gerente Predial)',
    items: [
      { id: 'p1', label: 'Reaperto torquimétrico de conexões e barramentos principais (QGBT)', category: 'Conexões', status: 'conforme' },
      { id: 'p2', label: 'Inspeção e teste de integridade dos Protetores de Surto (DPS)', category: 'Proteção', status: 'conforme' },
      { id: 'p3', label: 'Teste funcional de atuação de disjuntores e dispositivos DR', category: 'Dispositivos', status: 'conforme' },
      { id: 'p4', label: 'Termografia infravermelha para detecção de pontos quentes sob carga', category: 'Termografia', status: 'conforme' },
      { id: 'p5', label: 'Limpeza interna, despoeiramento e desumidificação de painéis', category: 'Limpeza', status: 'conforme' },
    ],
  },
  {
    id: 'pm2',
    code: 'PMOC-2026-002',
    planType: 'pmoc',
    discipline: 'climatizacao',
    periodicity: 'mensal',
    clientId: 'c1',
    clientName: 'Roberto Silva',
    equipmentName: 'Sistema VRF Daikin 18 HP (Escritórios 3º Andar)',
    technicianName: 'Mateus Rossi',
    date: '2026-09-08',
    generalStatus: 'aprovado',
    technicianNotes: 'Limpeza bactericida concluída. Filtros lavados e parâmetros de pressão de gás em perfeita conformidade.',
    clientSignatureName: 'Roberto Silva (Diretor)',
    items: [
      { id: 'p6', label: 'Higienização e aspersão bactericida nas serpentinas evaporadoras', category: 'Evaporadora', status: 'conforme' },
      { id: 'p7', label: 'Limpeza e desinfecção de bandejas e drenos de condensado', category: 'Drenagem', status: 'conforme' },
      { id: 'p8', label: 'Medição de pressão de sucção/descarga e superaquecimento', category: 'Ciclo Frigorigêneo', status: 'conforme' },
      { id: 'p9', label: 'Medição da corrente elétrica de compressores e motoventiladores', category: 'Motores', status: 'conforme' },
    ],
  },
  {
    id: 'pm3',
    code: 'PGM-2026-003',
    planType: 'pgm',
    discipline: 'hidraulica',
    periodicity: 'mensal',
    clientId: 'c3',
    clientName: 'Carlos Pereira',
    equipmentName: 'Conjunto de Bombas de Recalque e Incêndio Schneider 5CV',
    technicianName: 'Mateus Rossi',
    date: '2026-09-05',
    generalStatus: 'com_ressalvas',
    technicianNotes: 'Bomba 1 plenamente operacional. Bomba 2 apresentou leve gotejamento no selo mecânico, programada substituição.',
    clientSignatureName: 'Carlos Pereira (Gerente Predial)',
    items: [
      { id: 'p10', label: 'Teste operacional e comutação automática das bombas de recalque', category: 'Bombas', status: 'conforme' },
      { id: 'p11', label: 'Verificação de selos mecânicos, gaxetas e estanqueidade', category: 'Estanqueidade', status: 'nao_conforme' },
      { id: 'p12', label: 'Inspeção e teste de pressostatos e manômetros da rede', category: 'Pressurização', status: 'conforme' },
      { id: 'p13', label: 'Teste de bombas de combate a incêndio e pressurização de hidrantes', category: 'Incêndio', status: 'conforme' },
    ],
  },
];

